### ISSUE TITLE
3. Eklenmesi gereken meta html kodları

### ISSUE THREAD

**Issue by t3nGri** [acikkaynak/deprem-yardimi#109]
Web sitesi, twitter'da yalnızca tam url girildiğinde card veriyor. Bu eklemeler "depremyardim.com" yazıldığında da card vermesini sağlayacak.

```
<meta property="og:site_name" content="depremyardim.com" />
<meta name="twitter:site_name" content="depremyardim.com" />
```

**Comment by t3nGri** [comment]
Ek olarak dün ile bugünün arama sonuçları değişti,

title içeriğini "Deprem Yardım Bekleyen Çağrılar" yerine -> "Deprem Yardım Çağrısı ve Arama Kurtarma" olarak yenileyebilirsen, işimize yarayabilir.

**Comment by sustartx** [comment]
Tamamlandı.
