### ISSUE TITLE
Toplu isim girme

### ISSUE THREAD

**Issue by metinsut** [acikkaynak/deprem-yardimi#11]
### Bazı twetlerde toplu isim var, buna bir kısa yol oluşturabiliriz.

![IMG_20230207_214816](https://user-images.githubusercontent.com/23661667/217338226-2dfb7c8b-49b4-4788-9a68-85b0370edbdb.jpg)

**Comment by sustartx** [comment]
Aynı form içerisinde aileden olmayan farklı kişilerin bilgileri girilerek yanlış adreste yanlış kişinin aranmasına sebep olacağı için yapmamayı tercih ediyoruz.
