### ISSUE TITLE
Yarım İsteyenler bölümünde mobil submit sorunu

### ISSUE THREAD

**Issue by t3nGri** [acikkaynak/deprem-yardimi#114]
Mobile'de yardım isteyenler bölümünde, ad veya başka bir sorgu girince gönder/ara/submit yapılamıyor.

![depremyardim-yardimisteyenler](https://user-images.githubusercontent.com/76410812/217684305-7c718f4c-c6aa-4673-9247-e55cb0c52d4e.jpeg)

**Comment by Yekez** [comment]
![Screenshot_2023-02-09-04-48-29-437_com android chrome](https://user-images.githubusercontent.com/64737937/217696160-15c163e4-72e9-4942-97bd-bf9cbec298a5.jpg)
Ben arama yapabiliyorum hocam. Sorunu biraz daha detaylı yazabilir misin?

**Comment by t3nGri** [comment]
Merhabalar, issue'yi discord'dan belirttim, daha sonradan issue açmamı istediler. Problem çözüldü ekrandaki ara ve temizle butonları eklendi. Ancak yoğunluktan issue kapatılmamış.
