### ISSUE TITLE
lutfen aynı kişiyi tekrar girmeyiniz ibaresi !!!

### ISSUE THREAD

**Issue by aibe-1** [acikkaynak/deprem-yardimi#16]
lutfen aynı kişiyi tekrar girmeyiniz diye bir ibare yazılmalı acıklamaya farkedilecek sekilde boylece yonlendırebilirz

**Comment by metinsut** [comment]
altta search yapabileceği bir input var oraya işaret edilebilir.

**Comment by sustartx** [comment]
Bir alert ile uyarı ekledik.
