### ISSUE TITLE
Composer Dependencies required a PHP version

### ISSUE THREAD

**Issue by Mem8** [acikkaynak/deprem-yardimi#2]
depremyardim sitesi üzerinde php version hatası alıyorum. Desktop üzerinde Chrome, Firefox, Brave ve Edge tarayıcıları üzerinde aynı hatayı alıyorum. Ayrıca Mobil tarayıcılarda da aynı hatayı alıyorum. Mobilde Chrome, Firefox ve Brave tarayıcıları ile aynı hatayı alıyorum.

`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 5.5.38. in /home/deprem/public_html/vendor/composer/platform_check.php on line 25`

**Comment by ZgrK** [comment]
Bence bu issue kapatabiliriz artık bu durum çözüldü
