### ISSUE TITLE
Livewire integration

### ISSUE THREAD

**Issue by FurkanGM** [acikkaynak/deprem-yardimi#20]
Homepage form, should be convert to livewire for security and flexible

**Comment by ZgrK** [comment]
Anasayfada ki form'a yeni bir input gerekiyor bu input google map url girilmesi için ayriyetten burada ki video urlsi dae eklenebilir video materyalleri buradan ulaşılabilir https://discord.com/channels/1072074800622739476/1072090981039603796/1072669364228210718 


https://user-images.githubusercontent.com/879674/217397372-afb0f9a7-3400-4d43-86c7-b59495d1eded.mp4

**Comment by ZgrK** [comment]
Soyle bir istek daha var 

Veri Girişi Alanına Koordinat Ekleme (URL veya Enlem,Boylam direk yazılabilir URL ise ön yüz ona göre gelir. Enlem Boylam ise ona göre)
