### ISSUE TITLE
adres tarifi width 

### ISSUE THREAD

**Issue by ahmetceyhan** [acikkaynak/deprem-yardimi#30]
adres tarifi width yazı uzunluğu ile birlikte aşırı büyüyüp taşıyor, max verilip alt satıra geçmesi sağlanabilir
![Ekran Resmi 2023-02-08 03 37 38](https://user-images.githubusercontent.com/9299313/217400245-673ed6f0-1d0e-4982-8bbe-b178c57a19f4.png)

**Comment by Yekez** [comment]
bu halloldu sanırım şu an böyle bir sıkıntı yok gibi duruyor @sustartx

**Comment by ahmetceyhan** [comment]
chrome ve safaride devam etmekte, firefox da düzelmiş

**Comment by sustartx** [comment]
Link alanına girilen verilerde haritaya yönlendirme yaptık, adres tarifine girilen verilerde link olursa uzamaya devam ediyor. Adres içinden linki ayırmak gerektiğinden şimdilik o sütun için bir çalışma yapılmıyor.

**Comment by eece** [comment]
@sustartx  ilgili selectore word-break: break-all; verilerek linklerdeki taşma da düzeltilebilir.

**Comment by eece** [comment]
https://github.com/acikkaynak/deprem-yardimi/pull/100 pr açtım inceleyebilir misiniz? @sustartx

**Comment by sustartx** [comment]
Onayladım, teşekkürler.
