### ISSUE TITLE
Mujde verici

### ISSUE THREAD

**Issue by denizhantoy** [acikkaynak/deprem-yardimi#36]
Arkadaşlar yardım isteyen mesajlardaki isim soyisim leri filtreleyip kalabalığı önlemek istiyorum. Ayrıca hastane verilerinden kontrol edip yakınınız bulunmuştur şu hastanededir gibi telefon bırakanlara mesaj atılabilir. Güvenlik sorunu oluşurmu? Oluşmayacaksa 
telegram : @denizhanbey telegram üzerinden irtibata geçin hızlıca takım çalışması yapalım.

**Comment by sustartx** [comment]
Vatandaşların güvenlik riskinden dolayı yapmamayı tercih ettik.
