### ISSUE TITLE
Performans: Gonderilen assetlerin cok buyuk bir kismi initial load sirasinda kullanilmiyor

### ISSUE THREAD

**Issue by unworthyEnzyme** [acikkaynak/deprem-yardimi#47]
Ozellikle bootsrap.min.css' in %96.4'si kullanilmiyor. Olcmek icin chrome'da [coverage](https://developer.chrome.com/docs/devtools/coverage/) tool'unu kullanabilirsiniz.

**Comment by sustartx** [comment]
Gerekli temizlik yapıldı.
