### ISSUE TITLE
Performans: Lighthouse score'u cok dusuk sitenin

### ISSUE THREAD

**Issue by unworthyEnzyme** [acikkaynak/deprem-yardimi#48]
[Sonuclar](https://pagespeed.web.dev/report?url=https%3A%2F%2Fdepremyardim.com%2F)'a buradan bakabilirsiniz. Bu aslinda actigim [#47](https://github.com/acikkaynak/deprem-yardimi/issues/47) nolu issue ile de iliskili. Sitenin LCP'si 6.1s ki bu oldukca kotu bir deger, en kotu 2.5s ve altinda olmasi gerekiyor en azindan siteye ziyaretlerin %75'ini 2.5 saniye altinda olmasi gerekiyor.

**Comment by unworthyEnzyme** [comment]
Yapilabilecekler arasinda #47 deki sorunu cozmenin yaninda font gondermekten vazgecilebilinir. Gonderilen iki font diger her asset'den daha buyuk. Ve sitenin yapmasi gereken sey icin tamamen gereksiz.

**Comment by sustartx** [comment]
Çalışma yaptık.
