### ISSUE TITLE
BUG: Eksik Validationlar

### ISSUE THREAD

**Issue by hgunay** [acikkaynak/deprem-yardimi#57]
Dummy datalar ile form girişi yapılabiliyor. Bu tip durumlar injectionların yapılabilmesine sabep oluyor.

![image](https://user-images.githubusercontent.com/19264860/217517906-60d1b0ef-7329-4c8e-9eaf-17e735e39a7c.png)

**Comment by sustartx** [comment]
Hangi inputlar için validation öneriyorsunuz? Biz gerekli gördüklerimize ekledik.

**Comment by hgunay** [comment]
> Hangi inputlar için validation öneriyorsunuz? Biz gerekli gördüklerimize ekledik.

1. Alanların tümüne uzunluk sınırlaması eklenmesi
2. Telefon no alanına sadece telefon formatı ile giriş yapılabilmesi ve sadece numeric kabul etmesi
3. Text alanlarda alphanumeric karakterler haricinde sadece "-", ".", "/", "_" gibi belirli karakterlere izin verilmesi
4. Bulunan kat için numeric karakterleri kabul etmesi
5. Adres tarifi max.1000 karakter ya da db'de tanımlı olduğu değer neyse o kabul edilebilir. Ancak sınırlama eklenmesi önemli.

**Comment by sustartx** [comment]
Zor durumda olan kişilerin veri girişi sırasında validation ile uğraşmaması için sadece bazı alanların doğrulamasını yaptık.
