### ISSUE TITLE
Sağ üst köşeye diğer sitelerin iconları koyulacak.

### ISSUE THREAD

**Issue by myagizmaktav** [acikkaynak/deprem-yardimi#60]
Sağ üst köşeye diğer sitelerin iconları koyulacak.
Sağ üst köşeye 25x25px yuvarlak olarak diğer sitelerimiz iconları koyulacak ve bu iconlar tıklandığında diğer siteleri yeni sayfada açıcak.
Ve eğer üstlerine gelindiğinde kısaca sitelerin ne konuda çözüm ürettiği hakkında açıklama çıkıcak.

Siteler
Deprem.io
afetharita.com
discord.gg/itdepremyardim

**Comment by sustartx** [comment]
Linkler eklendi.
