### ISSUE TITLE
Depremzedeler son durum

### ISSUE THREAD

**Issue by ahmetarsiv** [acikkaynak/deprem-yardimi#66]
Depremzedelerin son durumu hakkında bir bilgi tablosu eklememiz mümkünmüdür?

örnek:
vefat etti
kurtarıldı,
kurtarıldı ise hangi hastahanede,
bekliyor,

**Comment by sustartx** [comment]
Verilecek bilgilerin doğruluğundan emin olamayacağımız için yapmamayı tercih ediyoruz.
