### ISSUE TITLE
kayıtlı yardım talepleri alanı

### ISSUE THREAD

**Issue by SebahattinDemir** [acikkaynak/deprem-yardimi#82]
Kayıtlı yardım talepleri alanında şehir isimleri tıklanabilir halde. Tıklama yapıldığında ana sayfanın üstüne kaydırıyor sayfayı. Burada ki tıklanabilir olmayı kaldırılabilir mi zaten bir fonksiyona yönlendirme olmuyor anladığım kadarıyla

**Comment by sustartx** [comment]
Metin haline getirdik.
