### ISSUE TITLE
Twitter meta etiketi, ufak bir değişiklik.

### ISSUE THREAD

**Issue by t3nGri** [acikkaynak/deprem-yardimi#91]
Twitter card'ı küçük görünüyor:
![image](https://user-images.githubusercontent.com/76410812/217620171-c89b5ecc-449b-4de7-b3bf-992163531a4a.png)

card'ı büyütmek için, aşağıdaki summary kod'unu 
`<meta name="twitter:card" content="summary">`

bu kodla değiştirmek gerekiyor:
`<meta name="twitter:card" content="summary_large_image">`

**Comment by sustartx** [comment]
Tamamlandı.
