### ISSUE TITLE
Adres Bildirim Formu zorunlu alanlar girilmeden kayıt edilebilmesi

### ISSUE THREAD

**Issue by ilyastunch** [acikkaynak/deprem-yardimi#93]
## Hata Tanımı
Adres Bildirim Formu zorunlu alanlar girilmeden 
kayıt edilebilmesi

## Hatayı nasıl aldığınızı adım adım açıklayın

1.  Deprem Yardım Anasayfasına gidin
2. Adres Bildirim Formunda Sehir alanını girin
3.İlçe/Mahalle zorunlu alanlarını boş bırakın
4. Diğer zorunlu alanları girin
5. Kaydet butonına basın

## Beklenen Davranış
Kaydetmenin gerçekleşmemesi ve zorunlu alanları doldurun uyarısının gelmesi

##Varolan Davranış
Kaydetme işlemini gerçekleştiriyor.  Yardım isteyenler listesinde görünüyor.

## Masaüstü Bilgileri
- İşletim Sistemi: Windows 10 x64
- Tarayıcı: Chrome
- Sürüm: Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by berkansahin** [comment]
Ben kontrol ettiğimde böyle bir hata göremedim düzelmiş olabilir mi acaba ? Rica etsem loom kaydı gönderebilir misiniz ?

<img width="727" alt="Screenshot 2023-02-09 at 00 16 04" src="https://user-images.githubusercontent.com/4026967/217653252-692a020c-3cf3-48cc-9eea-371c24df6de2.png">

**Comment by CanerErgez** [comment]
Teyitledim, herhangi bir sorun yok.

**Comment by sustartx** [comment]
Geliştirme yapıldı : #103

**Comment by ilyastunch** [comment]
@CanerErgez @berkansahin Geliştirme yapıldı fixlendi teşekkürler
